name: turksell
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # Localization Library
  flutter_localizations:
    sdk: flutter

  # DI
  provider: ^4.3.2+2

  # Dependency injection

  inject:
    git:
      url: https://github.com/yes-soft-de/inject.dart.git
      path: package/inject
  # Camera
  camera: ^0.5.8+7

  # Video
  video_player: ^0.11.0

  # Paths
  path_provider: ^1.6.18

  # Shared Prefs
  shared_preferences: ^0.5.12

  # Open Url in Chrome
  url_launcher: ^5.7.0

  # Network Agent
  dio: ^3.0.10
  dio_flutter_transformer: ^3.0.2
  dio_http_cache: ^0.2.11

  # Pair and Other Types
  analyzer_plugin: ^0.3.0

  # String validation
  validators: ^2.0.1

  # Svg Loader
  flutter_svg: ^0.19.0

  # Streams and RX
  rxdart: ^0.24.1

  # ORM, Database SQL
  sqfentity: ^1.4.0+1

  # Firebase Libs
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_analytics: ^6.0.0
  firebase_remote_config: ^0.4.0
  cloud_firestore: ^0.14.0+2

  # Google Sign In
  google_sign_in: ^4.5.4
  sign_in_with_apple: ^2.5.2

  # Localization
  gen_lang: 0.1.3

  # Internationalization
  intl: ^0.16.1
  intl_translation: ^0.17.10
  intl_utils: ^1.6.5

  # Toasts
  fluttertoast: ^7.1.1

  # UUID
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.1

  test: ^1.15.2

  inject_generator:
    git:
      url: https://github.com/yes-soft-de/inject.dart.git
      path: package/inject_generator

  # Generate Language Files
  lang_table: 0.2.0

  # Icons Generator
  flutter_launcher_icons: "^0.7.3"

flutter:
  uses-material-design: true

flutter_intl:
  enabled: false

